// 공통 에러 코드
export enum CommonErrorCode {
  INVALID_INPUT = "C001",
  ENTITY_NOT_FOUND = "C003",
  INTERNAL_SERVER_ERROR = "C004",
  INVALID_TYPE = "C005",
  ENTITY_ALREADY_EXISTS = "C006",
  VALIDATION_FAILED = "V001",
  IMAGE_URL_CONVERSION_FAILED = "I001",
}

// 비즈니스 에러 코드
export enum BusinessErrorCode {
  // 일반 비즈니스 에러
  BUSINESS_LOGIC_ERROR = "B001",

  // 사용자/고객 관련 에러
  USER_NOT_FOUND = "U001",
  CUSTOMER_NOT_FOUND = "CA001",
  CUSTOMER_ADDRESS_NOT_FOUND = "CA002",
  CUSTOMER_ADDRESS_ALREADY_EXISTS = "CA003",

  // 주문 관련 에러
  ORDER_NOT_FOUND = "O001",
  ORDER_ALREADY_COMPLETED = "O002",
  ORDER_ALREADY_CANCELLED = "O003",
  INVALID_ORDER_MENU = "O004",
  ORDER_ACCEPT_FAILED = "O005",
  ORDER_REJECT_FAILED = "O006",
  ORDER_COMPLETE_FAILED = "O007",
  ORDER_CANCEL_FAILED = "O008",
  INVALID_ORDER_STATUS = "O009",

  // 결제 관련 에러
  PAYMENT_FAILED = "P001",
  PAYMENT_ALREADY_PROCESSED = "P002",
  PAYMENT_AMOUNT_MISMATCH = "P003",

  // 매장 관련 에러
  STORE_NOT_FOUND = "S001",
  STORE_CLOSED = "S002",
  STORE_UNAVAILABLE = "S003",
  SUBSCRIPTION_NOT_FOUND = "S004",
  SUBSCRIPTION_UPDATE_FAILED = "S005",
}
