import Providers from "@/providers";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/reset.css";
import PullToRefreshWrapper from "@/components/ui/pullToRefresh";
import classNames from "classnames";
import * as style from "./layout.css";

if (
  process.env.NEXT_RUNTIME === "nodejs" &&
  process.env.NEXT_PUBLIC_VERCEL_MSW_ENV === "development"
) {
  const { worker } = await import("../mocks/server");

  worker.listen();
}

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames(pretendard.variable, style.container)}>
        <Providers>
          <PullToRefreshWrapper>
            <div className={style.main}>{children}</div>
          </PullToRefreshWrapper>
          <div id="bottom-sheet" />
        </Providers>
      </body>
    </html>
  );
}
